name: Build java project

on: 
  push:
    branches: 
      - 'main'
    paths: 
      - src/**
  pull_request: 
    branches: 
      - 'main'
    types: 
      - closed
  workflow_dispatch:
  
jobs: 
  build-java-project:
   # runs-on: ubuntu-latest
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
       os: [ubuntu-latest, mac-OS-latest, windows-latest]
       java: [8, 11.0.3]
      max-parallel: 3
       
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java}}
          java-package: jdk
      - name: Build with Maven
        run: mvn verify
