name: Build java project

on: 
  push:
    branches: 
      - 'main'
    paths: 
      - src/**
  pull_request: 
    branches: 
      - 'main'
    types: 
      - closed
  workflow_dispatch:
  schedule:
  - cron: '30 15 31 AUG 3'
  
#┌───────────── minute (0 - 59)
#│ ┌───────────── hour (0 - 23)
#│ │ ┌───────────── day of the month (1 - 31)
#│ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
#│ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
#│ │ │ │ │
#│ │ │ │ │
#│ │ │ │ │
#* * * * *

jobs: 
  build-java-project:
   # runs-on: ubuntu-latest
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
       os: [ubuntu-latest, mac-OS-latest, windows-latest]
       java: [8, 11.0.3]
      max-parallel: 3
       
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java}}
          java-package: jdk
          distribution: adopt
      - name: Build with Maven
        run: mvn verify
