name: Build java project

on: 
  push:
    branches: 
      - 'main'
    paths: 
      - src/**
  pull_request: 
    brances: 
      - 'main'
    types: 
      - closed
  workflow_dispatch:
  
  jobs: 
    build-java-project:
      runs_on: ubuntu
      
      steps:
        - name: Checkout project
          uses: actions/checkout@v2
        - name: Set up JDK 12
          uses: actions/setup-java@v2
          with:
            java-version: '12'
            distribution: 'adopt'
        - name: Build with Maven
          run: mvn verify
